image: registry.gitlab.memleak.pl:443/flat/build-images/android

before_script:
  - export PATH=$PATH:/usr/local/android-sdk-linux/platform-tools/
  - export GRADLE_USER_HOME=/cache/.gradle

stages:
  - build
  - test

cache:
    paths:
    - /root/.gradle

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    expire_in: "2 weeks"
    paths:
    - app/build/outputs/

build-release:
  stage: build
  script:
    - echo $KEYSTORE_FILE | base64 -di > app/store.jks
    - echo storePassword=$KEYSTORE_PASS > keystore.properties
    - echo keyPassword=$KEY_PASS >> keystore.properties
    - echo keyAlias=flat >> keystore.properties
    - echo storeFile=store.jks >> keystore.properties
    - ./gradlew assembleRelease
  artifacts:
    paths:
    - app/build/outputs/
#  only:
#    - /^v.*$/

unitTests:
  stage: test
  script:
    - ./gradlew test
